using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace UnityVulkanDriverGuard.Editor
{
    internal sealed class DriverGuardBuildProcessor : IPostprocessBuildWithReport
    {
        public int callbackOrder => 10000;

        public void OnPostprocessBuild(BuildReport report)
        {
            var target = report.summary.platform;
            if (target != BuildTarget.StandaloneWindows64 && target != BuildTarget.StandaloneLinux64)
                return;

            var outputPath = Path.GetFullPath(report.summary.outputPath);
            var buildDirectory = Directory.Exists(outputPath)
                ? outputPath
                : Path.GetDirectoryName(outputPath);
            if (string.IsNullOrEmpty(buildDirectory))
                throw new BuildFailedException("Cannot determine the standalone player output directory.");

            var windows = target == BuildTarget.StandaloneWindows64;
            var playerName = windows ? "UnityPlayer.dll" : "UnityPlayer.so";
            var originalPlayerName = windows ? "UnityPlayerI.dll" : "UnityPlayerI.so";
            var architecture = "x86_64";

            var packageRoot = Environment.GetEnvironmentVariable("UVDG_PACKAGE_ROOT");
            if (string.IsNullOrWhiteSpace(packageRoot))
            {
                var package = UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(DriverGuardBuildProcessor).Assembly);
                if (package == null)
                    throw new BuildFailedException("Cannot resolve the Unity Vulkan Driver Guard package path.");
                packageRoot = package.resolvedPath;
            }

            var platform = windows ? "Windows" : "Linux";
            var proxySource = Path.Combine(packageRoot, "Native~", platform, architecture, playerName);
            var playerPath = Path.Combine(buildDirectory, playerName);
            var originalPlayerPath = Path.Combine(buildDirectory, originalPlayerName);
            var temporaryProxy = playerPath + ".uvdg.tmp";

            if (!File.Exists(proxySource))
                throw new BuildFailedException($"Driver Guard native proxy is missing: {proxySource}");
            if (!File.Exists(playerPath))
                throw new BuildFailedException($"Unity player library is missing: {playerPath}");
            if (File.Exists(originalPlayerPath))
                throw new BuildFailedException($"Build output was already patched: {originalPlayerPath}");

            File.Copy(proxySource, temporaryProxy, true);
            try
            {
                File.Move(playerPath, originalPlayerPath);
                File.Move(temporaryProxy, playerPath);
            }
            catch
            {
                if (!File.Exists(playerPath) && File.Exists(originalPlayerPath))
                    File.Move(originalPlayerPath, playerPath);
                throw;
            }
            finally
            {
                if (File.Exists(temporaryProxy))
                    File.Delete(temporaryProxy);
            }

            var configPath = Path.Combine(buildDirectory, "UnityVulkanDriverGuard.ini");
            File.WriteAllText(configPath, CreateConfig(DriverGuardSettings.instance, windows),
                new UTF8Encoding(false));
            Debug.Log($"[UnityVulkanDriverGuard] Installed pre-render proxy: {playerPath}");
        }

        internal static string CreateConfig(DriverGuardSettings settings, bool windows)
        {
            var output = new StringBuilder();
            output.AppendLine("; Generated by Unity Vulkan Driver Guard.");
            output.AppendLine("; DriverDenyList uses UE5-style numeric comparisons.");
            output.AppendLine("[Global]");
            output.AppendLine($"MinimumVulkanVersion={settings.minimumVulkanMajor}.{settings.minimumVulkanMinor}");
            AppendPolicy(output, "GPU_NVIDIA", settings.nvidia, windows);
            AppendPolicy(output, "GPU_AMD", settings.amd, windows);
            AppendPolicy(output, "GPU_INTEL", settings.intel, windows);
            return output.ToString();
        }

        private static void AppendPolicy(StringBuilder output, string section,
            VendorDriverPolicy policy, bool windows)
        {
            output.AppendLine();
            output.AppendLine($"[{section}]");
            var suggestedVersion = windows ? policy.windowsSuggestedVersion : policy.linuxSuggestedVersion;
            output.AppendLine($"SuggestedDriverVersion={Safe(suggestedVersion)}");
            output.AppendLine($"DownloadURL={Safe(policy.downloadUrl)}");

            var platform = windows ? DriverRulePlatform.Windows : DriverRulePlatform.Linux;
            foreach (var rule in policy.denyList.Where(rule =>
                         rule != null &&
                         (rule.platform == DriverRulePlatform.All || rule.platform == platform) &&
                         !string.IsNullOrWhiteSpace(rule.comparison)))
            {
                output.Append("+DriverDenyList=");
                output.Append(Safe(rule.comparison));
                if (!string.IsNullOrWhiteSpace(rule.reason))
                    output.Append('|').Append(Safe(rule.reason));
                output.AppendLine();
            }
        }

        private static string Safe(string value)
        {
            return (value ?? string.Empty).Replace("\r", " ").Replace("\n", " ").Trim();
        }
    }
}
